[build]
  command = "composer install --no-dev --optimize-autoloader --no-scripts"
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
 from = "/*"
  to = "/.netlify/functions/hello" # <--- Cambiamos index por hello
  status = 200
  force = true