[build]
  command = "composer install --no-dev --optimize-autoloader --no-scripts"
  publish = "public"

[functions]
  directory = "netlify/functions"
  included_files = ["app/**", "config/**", "database/**", "resources/**", "routes/**", "vendor/**", ".env", "bootstrap/**"]

[[redirects]]
  from = "/*"
  to = "index"
  status = 200
  force = true


  #